import os
from snakemake.utils import min_version

min_version("7.32.4")

configfile: "config.yml"

### create log dirs

logdirs = ["default", "all", "create_manifest"]

for d in logdirs:
    os.makedirs(os.path.join("logs", d), exist_ok = True)

## create outdir

os.makedirs(os.path.join(config["outdir"], config["proj_name"]), exist_ok = True)

### load rules

alloutput = list()

if config["exp_type"] == "t":
    alloutput.append(config["outdir"] + "/" + config["proj_name"] + "/manifest.tsv")
if config["exp_type"] == "m":
    alloutput.append("TODO add output")

rule all:
    input:
        alloutput

include: "rules/create_manifest.smk"