import os
from snakemake.utils import min_version

min_version("7.32.4")

configfile: "config.yml"

### create log dirs

logdirs = ["default", "all", "create_manifest", "import_fastq", "dada2"]

for d in logdirs:
    os.makedirs(os.path.join("logs", d), exist_ok = True)

## create outdir

os.makedirs(os.path.join(config["outdir"], config["proj_name"]), exist_ok = True)

## sample names

SAMPLES = [s[:-len(".fastq.gz")] for s in os.listdir(config["raw_data"])]

## output handling

alloutput = list()
alloutput.append(config["outdir"] + "/" + config["proj_name"] + "/reads_raw/demux.qza")
alloutput.append(config["outdir"] + "/" + config["proj_name"] + "/reads_raw/demux.qzv")

rule all:
    input:
        alloutput

### load rules

include: "rules/create_manifest.smk"
include: "rules/import_fastq.smk"
include: "rules/dada2.smk"