########################
# IMPORTANT INFORMATION:
#
# Variables commented with [ #cluster# ] must be
# changed accordingly in cluster_config.yml
########################


### General ###

proj_name: cereal_16S                                     #-------#    Project name
outdir: /scratch/salias/projects                          #-------#    Directory with all projects
raw_data: /home/salias/data/cereal_bacteria               #-------#    Directory with FASTQ files
metadata: /home/salias/projects/sporeflow/metadata.tsv    #-------#    Metadata file. Modify it with your experiment details (it needs to have metadata.tsv as filename)
type: 16S                                                 #-------#    Region sequenced: 16S (bacteria, not implemented yet) or ITS (fungi)


### Databases ###

db_dir: /home/salias/data/sf_databases/Greengenes    #-------#    Directory where database is stored
db_file: gg_2022_10_backbone_full_length.nb.qza      #-------#    Database filename


### Sequences ###

end: paired    #-------#    Options: paired (single end not supported for now)
r1_suf: R1     #-------#    Forward read suffix (DO NOT CHANGE)
r2_suf: R2     #-------#    Reverse read suffix (DO NOT CHANGE)


### Cutadapt ###

use_cutadapt: True              #-------#    True if you want to use Cutadapt, False otherwise (the rest of Cutadapt options will be ignored then)
cutadapt_trim_3_prime: True     #-------#    To trim (True) or not to trim (False) reverse complementary of primers in the 3' end
cutadapt_primer_f: 341F         #-------#    Forward primer name present in resources/[ITS/16S]_primers.tsv or custom sequence
cutadapt_primer_r: 805R         #-------#    Reverse primer name present in resources/[ITS/16S]_primers.tsv or custom sequence
cutadapt_n_threads: 2           #cluster#    Number of threads to use for multithreaded processing


### ITSxpress (IMPORTANT: If using 16S, set use_itsxpress to False) ###

use_itsxpress: False         #-------#    True if you want to use ITSxpress, False otherwise (the rest of ITSxpress options will be ignored then)
itsxpress_region: ITS2       #-------#    Regions ITS2, ITS1, and ALL can be selected
itsxpress_cluster_id: 1.0    #-------#    Percent identity for clustering reads (0.995-1). Set to 1 for exact dereplication
itsxpress_n_threads: 16      #cluster#    Number of threads to use for multithreaded processing (ITSxpress stops reducing runtime at about 10 cores)


### DADA2 ###

dada2_trim_left_f: 0       #-------#    Position at which forward read sequences should be trimmed due to low quality
dada2_trim_left_r: 0       #-------#    Position at which reverse read sequences should be trimmed due to low quality
dada2_trunc_len_f: 250     #-------#    Position at which forward read sequences should be truncated due to decrease in quality
dada2_trunc_len_r: 200     #-------#    Position at which reverse read sequences should be truncated due to decrease in quality
dada2_max_ee_f: 2          #-------#    Forward reads with number of expected errors higher than this value will be discarded
dada2_max_ee_r: 2          #-------#    Reverse reads with number of expected errors higher than this value will be discarded
dada2_trunc_q: 2           #-------#    Reads are truncated at the first instance of a quality score less than or equal to this value
dada2_min_overlap: 12      #-------#    Minimum length of the overlap required for merging the forward and reverse reads
dada2_n_threads: 60        #cluster#    Number of threads to use for multithreaded processing


### Taxonomic classification ###

taxonomy_n_threads: 2    #cluster#    Maximum number of concurrent worker processes


### Filter junk ###

kingdom_to_keep: d__Bacteria    #-------#    All sequencies not belonging to that kingdom will be discarded. Options available: k__Fungi, d__Bacteria (note the double underscore '_')
min_taxa_level: c__             #-------#    All sequences without annotations at least as specific as this taxonomic level will be discarded.
#---------------------------------------#    Available levels (note the double underscore '_'):
#---------------------------------------#      d__: Domain // k__: Kingdom
#---------------------------------------#      p__: Phylum (conservative)
#---------------------------------------#      c__: Class (recommended)
#---------------------------------------#      o__: Order (recommended)
#---------------------------------------#      f__: Family
#---------------------------------------#      g__: Genus
#---------------------------------------#      s__: Species (you will likely discard almost everything)


### Relative filtering ###

filtering_abundance: 0.01     #-------#    Minimum relative abundance for a feature to be retained
filtering_prevalence: 0.04    #-------#    Minimum portion of samples that a feature must have a relative abundance of at least `filtering_abundance` to be retained


### Diversity analysis ###

diversity_rarefaction_steps: 20                                 #-------#    Rarefaction depths to include
diversity_rarefaction_iterations: 10                            #-------#    Number of rarefied feature tables to compute at each step
diversity_beta_group_sign_method: permanova;permdisp;anosim     #-------#    Group significance test(s) to be applied in beta group significance (separated by ;). Options: permanova, anosim, permdisp
diversity_beta_n_threads: 4                                     #cluster#    Number of concurrent jobs to use in performing beta methods


### Differential abundance ###

abundance_collapse_levels: 5;6;7                                 #-------#    Taxonomic levels to collapse prior to ANCOM-BC.
#------------------------------------------------------------------------#    Levels must be separated with semicolons (;) and you must specify at least one level.
#------------------------------------------------------------------------#    Available levels:
#------------------------------------------------------------------------#      1: Domain // Kingdom
#------------------------------------------------------------------------#      2: Phylum
#------------------------------------------------------------------------#      3: Class
#------------------------------------------------------------------------#      4: Order
#------------------------------------------------------------------------#      5: Family (recommended)
#------------------------------------------------------------------------#      6: Genus (recommended)
#------------------------------------------------------------------------#      7: Species (try if you feel confident)
abundance_p_alpha: 0.05                                          #-------#    Significance level
abundance_barplot_threshold: 0.05                                #-------#    To exclude features from the barplot
abundance_file: /home/salias/projects/sporeflow/abundance.tsv    #-------#    File with metadata columns and reference levels used for differential abundance